version: '3'

services:
  db:
    image: mongo

  backend:
    image: node:14
    volumes:
      - ./:/backend
    ports:
      - '3000:3000'
    depends_on:
      - db
    command: bash -c 'cd /backend && yarn && yarn prod'
