version: '3'

services:
  db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: docker
      MONGO_INITDB_ROOT_PASSWORD: docker
    ports:
      - '27017:27017'
  web:
    image: bossabox-backend
    depends_on:
      - db
    ports:
      - '4000:4000'
